### ISSUE TITLE
Plugin Roadmap

### ISSUE THREAD

**Issue by bandantonio** [bandantonio/obsidian-apple-books-highlights-plugin#5]
## 1.3.0

- [ ] #12 

----

## ✅ 1.2.0 ([Release notes](https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/releases/tag/1.2.0))

- [x] #2 

----

## ✅ 1.1.1 ([Release notes](https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/releases/tag/1.1.1))

- [x] Fix escaped HTML entities: #3 
- [x] Fix escaped HTML entities: #4 

----

## ✅ 1.1.0 ([Release notes](https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/releases/tag/1.1.0))

- [x] Import highlights from a specific book
- [x] Option to import all books at startup of Obsidian

**Comment by bandantonio** [comment]
Closed in favor of [Milestones](https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/milestones)
